INCLUDEPATH += \
    $$PWD/src \
    $$PWD/src/linux \
    $$PWD/src/linux/udp \
    $$PWD/../MQTTSNPacket/src \
    /opt/android/openssl/ssl_1.1/include

SOURCES += \
    $$PWD/src/linux/udp/SensorNetwork.cpp \
    $$PWD/../MQTTSNPacket/src/MQTTSNConnectClient.c \
    $$PWD/../MQTTSNPacket/src/MQTTSNConnectServer.c \
    $$PWD/../MQTTSNPacket/src/MQTTSNDeserializePublish.c \
    $$PWD/../MQTTSNPacket/src/MQTTSNPacket.c \
    $$PWD/../MQTTSNPacket/src/MQTTSNSearchClient.c \
    $$PWD/../MQTTSNPacket/src/MQTTSNSearchServer.c \
    $$PWD/../MQTTSNPacket/src/MQTTSNSerializePublish.c \
    $$PWD/../MQTTSNPacket/src/MQTTSNSubscribeClient.c \
    $$PWD/../MQTTSNPacket/src/MQTTSNSubscribeServer.c \
    $$PWD/../MQTTSNPacket/src/MQTTSNUnsubscribeClient.c \
    $$PWD/../MQTTSNPacket/src/MQTTSNUnsubscribeServer.c \
    $$PWD/src/MQTTGWConnectionHandler.cpp \
    $$PWD/src/MQTTGWPacket.cpp \
    $$PWD/src/MQTTGWPublishHandler.cpp \
    $$PWD/src/MQTTGWSubscribeHandler.cpp \
    $$PWD/src/MQTTSNAggregateConnectionHandler.cpp \
    $$PWD/src/MQTTSNGWAdapter.cpp \
    $$PWD/src/MQTTSNGWAdapterManager.cpp \
    $$PWD/src/MQTTSNGWAggregateTopicTable.cpp \
    $$PWD/src/MQTTSNGWAggregater.cpp \
    $$PWD/src/MQTTSNGWBrokerRecvTask.cpp \
    $$PWD/src/MQTTSNGWBrokerSendTask.cpp \
    $$PWD/src/MQTTSNGWClient.cpp \
    $$PWD/src/MQTTSNGWClientList.cpp \
    $$PWD/src/MQTTSNGWClientRecvTask.cpp \
    $$PWD/src/MQTTSNGWClientSendTask.cpp \
    $$PWD/src/MQTTSNGWConnectionHandler.cpp \
    $$PWD/src/MQTTSNGWEncapsulatedPacket.cpp \
    $$PWD/src/MQTTSNGWForwarder.cpp \
    $$PWD/src/MQTTSNGWLogmonitor.cpp \
    $$PWD/src/MQTTSNGWMessageIdTable.cpp \
    $$PWD/src/MQTTSNGWPacket.cpp \
    $$PWD/src/MQTTSNGWPacketHandleTask.cpp \
    $$PWD/src/MQTTSNGWProcess.cpp \
    $$PWD/src/MQTTSNGWPublishHandler.cpp \
    $$PWD/src/MQTTSNGWQoSm1Proxy.cpp \
    $$PWD/src/MQTTSNGWSubscribeHandler.cpp \
    $$PWD/src/MQTTSNGWTopic.cpp \
    $$PWD/src/MQTTSNGateway.cpp \
    $$PWD/src/linux/Network.cpp \
    $$PWD/src/linux/Threading.cpp \
    $$PWD/src/linux/Timer.cpp \

HEADERS += \
    $$PWD/../MQTTSNPacket/src/MQTTSNConnect.h \
    $$PWD/../MQTTSNPacket/src/MQTTSNPacket.h \
    $$PWD/../MQTTSNPacket/src/MQTTSNPublish.h \
    $$PWD/../MQTTSNPacket/src/MQTTSNSearch.h \
    $$PWD/../MQTTSNPacket/src/MQTTSNSubscribe.h \
    $$PWD/../MQTTSNPacket/src/MQTTSNUnsubscribe.h \
    $$PWD/../MQTTSNPacket/src/StackTrace.h \
    $$PWD/src/linux/Network.h \
    $$PWD/src/linux/Threading.h \
    $$PWD/src/linux/Timer.h \
    $$PWD/src/linux/udp/SensorNetwork.h \
    $$PWD/src/MQTTGWConnectionHandler.h \
    $$PWD/src/MQTTGWPacket.h \
    $$PWD/src/MQTTGWPublishHandler.h \
    $$PWD/src/MQTTGWSubscribeHandler.h \
    $$PWD/src/MQTTSNAggregateConnectionHandler.h \
    $$PWD/src/MQTTSNGWAdapter.h \
    $$PWD/src/MQTTSNGWAdapterManager.h \
    $$PWD/src/MQTTSNGWAggregateTopicTable.h \
    $$PWD/src/MQTTSNGWAggregater.h \
    $$PWD/src/MQTTSNGWBrokerRecvTask.h \
    $$PWD/src/MQTTSNGWBrokerSendTask.h \
    $$PWD/src/MQTTSNGWClient.h \
    $$PWD/src/MQTTSNGWClientList.h \
    $$PWD/src/MQTTSNGWClientRecvTask.h \
    $$PWD/src/MQTTSNGWClientSendTask.h \
    $$PWD/src/MQTTSNGWConnectionHandler.h \
    $$PWD/src/MQTTSNGWDefines.h \
    $$PWD/src/MQTTSNGWEncapsulatedPacket.h \
    $$PWD/src/MQTTSNGWForwarder.h \
    $$PWD/src/MQTTSNGWLogmonitor.h \
    $$PWD/src/MQTTSNGWMessageIdTable.h \
    $$PWD/src/MQTTSNGWPacket.h \
    $$PWD/src/MQTTSNGWPacketHandleTask.h \
    $$PWD/src/MQTTSNGWProcess.h \
    $$PWD/src/MQTTSNGWPublishHandler.h \
    $$PWD/src/MQTTSNGWQoSm1Proxy.h \
    $$PWD/src/MQTTSNGWSubscribeHandler.h \
    $$PWD/src/MQTTSNGWVersion.h \
    $$PWD/src/MQTTSNGateway.h \
